<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Continuer</name>
   <tag></tag>
   <elementGuidId>528eb7c9-ef0f-45f2-865c-5497cab9a0b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.cf772ffae > button[name=&quot;action&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@name='action'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b90e06ac-7b4e-4860-ab16-6208a5d59b6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>853b277e-5e33-4a3e-a26d-8efe0a56fead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>action</value>
      <webElementGuid>63cbb227-9e6c-493b-aca9-743ab063c96d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>9486d9c3-3c32-4ccf-8512-8a2806d8d6de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c89f1057d c08709d93 cfdf7e7ce c948a708e cfbc31414</value>
      <webElementGuid>977e2c62-55e3-492f-a61b-da8f65d5b346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action-button-primary</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>de98d90b-5207-4266-aec9-a303740738ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continuer</value>
      <webElementGuid>16132279-76c9-42d8-8dc2-42404d4cd0d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;cb8b84e38 c75147bfb&quot;]/main[@class=&quot;c2c486cd4 login&quot;]/section[@class=&quot;ca775d19e _prompt-box-outer&quot;]/div[@class=&quot;c4209fc2d ce0449bc6&quot;]/div[@class=&quot;cf12edc27&quot;]/div[@class=&quot;ca920f895 ca8471e59&quot;]/form[@class=&quot;c210378a2 c2e165c71&quot;]/div[@class=&quot;cf772ffae&quot;]/button[@class=&quot;c89f1057d c08709d93 cfdf7e7ce c948a708e cfbc31414&quot;]</value>
      <webElementGuid>476a0888-51b8-41cc-baf6-2f36b02c0ccb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@name='action'])[2]</value>
      <webElementGuid>59667417-1094-49c9-bbcb-8596b0ed288c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mot de passe oublié ?'])[1]/following::button[1]</value>
      <webElementGuid>1b65aed7-2c15-4160-969c-7e3f638d806d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masquer le mot de passe'])[2]/following::button[1]</value>
      <webElementGuid>696316d7-df94-4f92-92b4-b2235c08edcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>8d9830c0-ba48-472f-b415-060058c7d652</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'action' and (text() = 'Continuer' or . = 'Continuer')]</value>
      <webElementGuid>8f46e448-a4d9-476c-9191-dec11614b1d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
