<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Liste des trajets_d-flex justify-content-_3daa63</name>
   <tag></tag>
   <elementGuidId>f095f3f3-4dc0-4c37-b5b7-c954c454065b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sidebar-element-printer']/div/div/div/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8d3e62c9-edf9-4f79-bf63-af5ec6144464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-flex justify-content-center sidebar__menu__item  open</value>
      <webElementGuid>e6d828ed-65ab-40b8-80d7-9d460ffa1906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/reservations</value>
      <webElementGuid>6dc68aca-d419-42ab-b04b-62f6e4501cdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar-element-printer&quot;)/div[@class=&quot;sidebar collapsed&quot;]/div[@class=&quot;d-flex justify-content-between flex-column w-100&quot;]/div[@class=&quot;d-flex flex-column mb-auto align-items-center&quot;]/a[@class=&quot;d-flex justify-content-center sidebar__menu__item  open&quot;]</value>
      <webElementGuid>ba1ad620-e3a3-48e2-9cc5-e68402a0c6c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidebar-element-printer']/div/div/div/a[2]</value>
      <webElementGuid>76e3a8d7-79ef-4091-a6b3-cca0eb30940f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Liste des trajets'])[1]/preceding::a[2]</value>
      <webElementGuid>8e0fe2b2-8968-4808-9b93-9e0823d753ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/reservations')]</value>
      <webElementGuid>99407635-d060-4c4f-bb5f-cffdcc219092</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>e91fb446-9241-48ad-8feb-e53ac509fc4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/reservations']</value>
      <webElementGuid>38689037-6ee2-48ca-a5f5-3fde4c377814</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
