<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Paramtres_img-profil small</name>
   <tag></tag>
   <elementGuidId>901e1ea3-496a-4e59-8cdf-a0148007e2f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.img-profil.small</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navbar-element-printer']/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1182f443-6723-408f-be1b-9e1fb9ac3230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>pf.png</value>
      <webElementGuid>01726800-a318-4dab-8c58-f745409e3a62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/_next/image?url=https%3A%2F%2Fbtob-experiments.cellar-c2.services.clever-cloud.com%2F1686670003422-Sans%2520titre.png&amp;w=48&amp;q=75 1x, /_next/image?url=https%3A%2F%2Fbtob-experiments.cellar-c2.services.clever-cloud.com%2F1686670003422-Sans%2520titre.png&amp;w=96&amp;q=75 2x</value>
      <webElementGuid>4200372c-59a4-4b2e-90f4-12775cf90bf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_next/image?url=https%3A%2F%2Fbtob-experiments.cellar-c2.services.clever-cloud.com%2F1686670003422-Sans%2520titre.png&amp;w=96&amp;q=75</value>
      <webElementGuid>8ebd6f5d-7a7d-4815-9bee-2b21e6a33ba9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>b88bde8e-259f-40e4-9ba6-c5e291111467</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0856c92f-44c4-4d58-805c-12faa7a141ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-profil small</value>
      <webElementGuid>abd37c25-c78f-4a93-ab8e-48fa6a325715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>d5c9ac6f-fb11-47f0-bfb1-a63ea4b16a6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>9fadbd44-eeae-470a-ba1e-709b9e1c2d39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>e7575d21-c00b-43cc-8723-6e3f98519f35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbar-element-printer&quot;)/div[@class=&quot;d-flex justify-content-end&quot;]/div[@class=&quot;img-profil small d-flex align-items-center justify-content-center text-sm-medium text-blue cursor-pointer&quot;]/img[@class=&quot;img-profil small&quot;]</value>
      <webElementGuid>5b83c4f9-37e1-4226-bb88-044043c1ccb8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbar-element-printer']/div/div/img</value>
      <webElementGuid>aa73ced0-e06e-4a00-8b3b-4922242eec22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Paramètres'])[1]/preceding::img[1]</value>
      <webElementGuid>0a9a1514-fd14-4bc2-aba2-2f3c04d55e19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gestion des comptes'])[1]/preceding::img[1]</value>
      <webElementGuid>0131de2b-1c06-4f3b-a818-4666d1c1fdca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='pf.png']</value>
      <webElementGuid>196c9265-467d-4179-94a2-2a0e493ad7d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>617e6666-f9c9-4c86-83ce-c6edd4bac46a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'pf.png' and @src = '/_next/image?url=https%3A%2F%2Fbtob-experiments.cellar-c2.services.clever-cloud.com%2F1686670003422-Sans%2520titre.png&amp;w=96&amp;q=75']</value>
      <webElementGuid>8ef2bd03-080a-4633-b553-8a4cb824d0c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
