<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Liste des rservations sinistres</name>
   <tag></tag>
   <elementGuidId>4525563f-332a-47b8-8583-8acfffd80009</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.h4-header-medium.me-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='body-element']/div[2]/div[2]/div/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>12c1c82f-9bef-4794-be66-df07afb67e3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h4-header-medium me-3</value>
      <webElementGuid>4aaca474-a289-4cb0-977c-2c45e7fc0044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Liste des réservations sinistrées</value>
      <webElementGuid>72302f8e-259d-4b6a-b163-c5a960d196c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;body-element&quot;)/div[@class=&quot;d-flex&quot;]/div[2]/div[@class=&quot;ps-40 pe-3 mt-32 align-items-center justify-content-center mx-auto mb-4&quot;]/div[@class=&quot;d-flex justify-content-between&quot;]/div[@class=&quot;d-flex align-items-center&quot;]/span[@class=&quot;h4-header-medium me-3&quot;]</value>
      <webElementGuid>dd01948e-b125-4feb-ac45-80c024b8856d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='body-element']/div[2]/div[2]/div/div/div/span</value>
      <webElementGuid>3dae493b-4e81-4e82-9b05-c14d9418e457</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='N° de réservation'])[1]/preceding::span[4]</value>
      <webElementGuid>e81cfbf1-ed08-426e-a450-45ad25c43157</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/span</value>
      <webElementGuid>6771d0d9-ad40-4279-929b-c98a62842a35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Liste des réservations sinistrées' or . = 'Liste des réservations sinistrées')]</value>
      <webElementGuid>a055fcc0-cba9-48f1-8767-584e0fbf1bcd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
