<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Paramtres</name>
   <tag></tag>
   <elementGuidId>1632707a-f0d1-438c-af45-39f02873d51c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.h4-header-medium</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='body-element']/div[2]/div[2]/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c13f956e-dd49-4c6f-a7ec-82ad7b4ef2d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h4-header-medium</value>
      <webElementGuid>b23f4f5e-7277-4daf-831d-4e3d7a21aafb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Paramètres</value>
      <webElementGuid>d594e872-75de-44fb-9c9e-43b74fbcf4c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;body-element&quot;)/div[@class=&quot;d-flex&quot;]/div[2]/div[@class=&quot;ps-40 pe-3 mt-32 align-items-center justify-content-center mx-auto mb-4&quot;]/div[1]/span[@class=&quot;h4-header-medium&quot;]</value>
      <webElementGuid>8a542ff0-4cb3-4053-baa3-078e39e797d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='body-element']/div[2]/div[2]/div/div/span</value>
      <webElementGuid>99db0d6e-0fad-44db-86ed-9d84f00d1a01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gestion des comptes'])[1]/preceding::span[1]</value>
      <webElementGuid>c9bda174-2cbe-4b4a-80bd-ad61df56fa7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Liste des utilisateurs'])[1]/preceding::span[1]</value>
      <webElementGuid>47bd63fb-5046-4efa-a8f9-a0f6a3310287</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/span</value>
      <webElementGuid>1a1cc254-685d-4ffb-b262-fdc9bbfc9273</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Paramètres' or . = 'Paramètres')]</value>
      <webElementGuid>fc921de5-2ab9-4ddc-b5f2-ad54c67bf216</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
