<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Liste des trajets</name>
   <tag></tag>
   <elementGuidId>5e6951a4-f09f-4dfe-baa4-509f72040287</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.h4-header-medium.me-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='body-element']/div[2]/div[2]/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1908314a-ebe5-4dc1-8f8b-339156c62614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h4-header-medium me-3</value>
      <webElementGuid>b442a1f9-2b30-4f05-823f-cdd0604a2408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Liste des trajets</value>
      <webElementGuid>f969279e-837e-4f78-8410-d0bd20126fac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;body-element&quot;)/div[@class=&quot;d-flex&quot;]/div[2]/div[@class=&quot;ps-40 pe-3 mt-32 align-items-center justify-content-center mx-auto mb-4&quot;]/div[@class=&quot;d-flex align-items-center&quot;]/span[@class=&quot;h4-header-medium me-3&quot;]</value>
      <webElementGuid>762be491-01a1-407e-af86-17d83670d0d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='body-element']/div[2]/div[2]/div/div/span</value>
      <webElementGuid>87b10587-3f7d-4268-93dc-d79fc17d5b4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/span</value>
      <webElementGuid>833cc31e-1bd0-49ce-8dc3-25254c0fbd11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Liste des trajets' or . = 'Liste des trajets')]</value>
      <webElementGuid>8607e90f-6fec-4b8a-a2eb-a1c8fbf38826</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
