<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Liste des rservations sinistres_svg</name>
   <tag></tag>
   <elementGuidId>3f10d793-7b1d-4c1a-8d16-484759d3afec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>81c76332-775b-4249-aa50-b745e2fed719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>608af38a-ae5a-48e0-aa07-eb26ad94089f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>3e2ea50e-5fed-44d9-a1b7-09b845922aef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>00deae60-936c-414c-ba88-4abcb6601c38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>c9f24161-21a5-418d-9f3d-08941149a953</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>502c26fd-e25a-4cd8-9d7a-479ff2d2d115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>#19191B</value>
      <webElementGuid>6d6ad9e8-7714-4fbf-b3ca-01b0ffd51677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar-element-printer&quot;)/div[@class=&quot;sidebar collapsed&quot;]/div[@class=&quot;d-flex justify-content-between flex-column w-100&quot;]/div[@class=&quot;d-flex flex-column&quot;]/div[@class=&quot;d-flex flex-column mb-auto align-items-center mb-58&quot;]/a[@class=&quot;d-flex justify-content-center sidebar__menu__item  open&quot;]/div[@class=&quot;sidebar__menu__item__text&quot;]/span[@class=&quot;d-flex undefined&quot;]/svg[@class=&quot;svg&quot;]</value>
      <webElementGuid>55f6ccfd-1df9-4762-b0a0-54b10e1f4928</webElementGuid>
   </webElementProperties>
</WebElementEntity>
